### ISSUE TITLE
Do not fail when `redirect_source` is empty or non-existing

### ISSUE THREAD

**Issue by ehmicky** [quarva/netlify-plugin-contextual-redirects#7]
When users install the plugin from the UI, their `netlify.toml` will not have any `inputs` for this plugin yet. In that case, this plugin should not make the user's build fail. Instead, the plugin should be a noop until the user decides to specify where the redirects files are.

Additionally it should be valid for users to specify a redirects file only for deploy preview, and not for production (for example).

This means the following errors:

https://github.com/quarva/netlify-plugin-contextual-redirects/blob/56b15f1befbaef7a78f8a1fd10bcfc60d76f8d1e/index.js#L38-L40

Should use `console.log()` + `return` instead of `failPlugin()` + `return`.

**Comment by culturestate** [comment]
This was added as a catch for inadvertent misconfigurations, where e.g. the user intended to specify a source but either didn't or added it to the wrong context. `failPlugin` seemed like the most appropriate action to take, since it throws a noticeable error in the deploy log but lets the build complete.

Is there a preferred method for alerting on errors like this, @ehmicky?

**Comment by culturestate** [comment]
This was added to catch inadvertent misconfigurations, where e.g. the user may have intended to specify a source but forgot or added it to the wrong context.

`failPlugin` seems more useful than `console.log` in this situation, since it throws a noticeable error in the deploy log but allows the build to continue. Is there a preferred way to throw a "bright" alert like this, @ehmicky?

**Comment by ehmicky** [comment]
Unfortunately not at the moment, but there is a feature request for `utils.build.warn()` that should handle this: https://github.com/netlify/build/issues/1248

How should the behavior be for users who would like to override their redirects file in deploy previews and branch deploys, but not in production (or vice-versa)?

**Comment by culturestate** [comment]
I refactored the way we look for active contexts, asking the user to specify an array of contexts in which we should run and a path in which we should look for `redirects_*` files. This way also allows users to add redirects for branch-specific deploys.

Can you have a look at this and let me know if it addresses your concerns, @ehmicky?

 https://github.com/quarva/netlify-plugin-contextual-redirects/commit/14785f70334c1781b186ff9fe99097fb0fc696d5

**Comment by culturestate** [comment]
I refactored the way we look for active contexts, asking the user to specify an array of contexts in which we should run and a path in which we should look for redirects_* files. This way also allows users to add redirects for branch-specific deploys.

Can you have a look at this and let me know if it addresses your concerns, @ehmicky? 

https://github.com/quarva/netlify-plugin-contextual-redirects/blob/refactor-inputs/index.js

**Comment by ehmicky** [comment]
Yes, thanks! :+1:
